### PR TITLE
Cleanup Token Projection artefacts

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
This PR cleans up the conditions and constraints introduced in #31 related to the token projection story.

**Release note**:

```action operator
The `kupid` extension for Gardener is only compatible with Gardener versions `>= v1.37`.
```

### CODE REVIEW

**Review by timebertt — APPROVED** [review]
/lgtm

**Review by ashwani2k — APPROVED** [review]
Thanks for the PR. 
Looks good to me. 

/lgtm

**Pull request merged**
